// Generated by Runku. Do not edit.
import type { DocumentId, RunkuTimestamp } from "@runku/client";

export interface RunkuFunctions {
  readonly "messages.send": { readonly kind: "mutation"; readonly visibility: "public"; readonly arguments: { readonly "body": string; readonly "clientSentAt": RunkuTimestamp; readonly "messageId": string; readonly "roomId": DocumentId<"rooms">; }; readonly result: { readonly "members": readonly ({ readonly "displayName": string; readonly "principalId": string; })[]; readonly "messages": readonly ({ readonly "body": string; readonly "clientSentAt": RunkuTimestamp; readonly "id": string; readonly "senderId": string; readonly "senderName": string; })[]; readonly "name": string; readonly "ownerId": string; } };
  readonly "profiles.me": { readonly kind: "query"; readonly visibility: "public"; readonly arguments: null; readonly result: (null) | ({ readonly "displayName": string; readonly "principalId": string; }) };
  readonly "profiles.upsert": { readonly kind: "mutation"; readonly visibility: "public"; readonly arguments: { readonly "displayName": string; }; readonly result: { readonly "displayName": string; readonly "principalId": string; } };
  readonly "rooms.create": { readonly kind: "mutation"; readonly visibility: "public"; readonly arguments: { readonly "name": string; }; readonly result: { readonly "room": { readonly "members": readonly ({ readonly "displayName": string; readonly "principalId": string; })[]; readonly "messages": readonly ({ readonly "body": string; readonly "clientSentAt": RunkuTimestamp; readonly "id": string; readonly "senderId": string; readonly "senderName": string; })[]; readonly "name": string; readonly "ownerId": string; }; readonly "roomId": DocumentId<"rooms">; } };
  readonly "rooms.get": { readonly kind: "query"; readonly visibility: "public"; readonly arguments: { readonly "roomId": DocumentId<"rooms">; }; readonly result: { readonly "members": readonly ({ readonly "displayName": string; readonly "principalId": string; })[]; readonly "messages": readonly ({ readonly "body": string; readonly "clientSentAt": RunkuTimestamp; readonly "id": string; readonly "senderId": string; readonly "senderName": string; })[]; readonly "name": string; readonly "ownerId": string; } };
  readonly "rooms.join": { readonly kind: "mutation"; readonly visibility: "public"; readonly arguments: { readonly "roomId": DocumentId<"rooms">; }; readonly result: { readonly "members": readonly ({ readonly "displayName": string; readonly "principalId": string; })[]; readonly "messages": readonly ({ readonly "body": string; readonly "clientSentAt": RunkuTimestamp; readonly "id": string; readonly "senderId": string; readonly "senderName": string; })[]; readonly "name": string; readonly "ownerId": string; } };
  readonly "rooms.list": { readonly kind: "query"; readonly visibility: "public"; readonly arguments: null; readonly result: readonly ({ readonly "joined": boolean; readonly "memberCount": bigint; readonly "name": string; readonly "roomId": DocumentId<"rooms">; })[] };
}

export interface RunkuDocuments {
  readonly "profiles": { readonly tableId: "tbl_20FA3EAZBBQDM15JKB3JD4GSSQ"; readonly indexes: { readonly "by_principal": "idx_1K60TW9YBHATH3652RS9GHSXEC"; }; readonly value: { readonly "displayName": string; readonly "principalId": string; } };
  readonly "rooms": { readonly tableId: "tbl_4AC90Z4SACVT1W9CEJR47JB9N2"; readonly indexes: { readonly "by_owner": "idx_1GM4YT2X7DQ49559KKDKZSA921"; readonly "by_name": "idx_67K1V0C2M3D9DT1RAPT6CK54JH"; }; readonly value: { readonly "members": readonly ({ readonly "displayName": string; readonly "principalId": string; })[]; readonly "messages": readonly ({ readonly "body": string; readonly "clientSentAt": RunkuTimestamp; readonly "id": string; readonly "senderId": string; readonly "senderName": string; })[]; readonly "name": string; readonly "ownerId": string; } };
}

export type RunkuFunctionName = keyof RunkuFunctions;
export type RunkuFunctionArguments<N extends RunkuFunctionName> = RunkuFunctions[N]["arguments"];
export type RunkuFunctionResult<N extends RunkuFunctionName> = RunkuFunctions[N]["result"];
