use std::{collections::BTreeSet, fmt::Write};

use runku_contracts::{Contract, DocumentSchemaV1};
use runku_releases::{FunctionType, FunctionVisibility};
use runku_schema::SchemaCatalog;

use crate::{BuildError, declarative::LoadedFunction};

pub(crate) const GENERATED_TYPES_MAX_BYTES: usize = 2 * 1024 * 1024;

pub(crate) fn generate_types(
    functions: &[LoadedFunction],
    schema: &DocumentSchemaV1,
    indexes: &SchemaCatalog,
) -> Result<Vec<u8>, BuildError> {
    let mut client_types = BTreeSet::new();
    for function in functions {
        collect_client_types(&function.arguments_contract, &mut client_types);
        collect_client_types(&function.result_contract, &mut client_types);
    }
    for table in &schema.tables {
        collect_client_types(&table.document_contract, &mut client_types);
    }
    let mut output = String::from("// Generated by Runku. Do not edit.\n");
    if !client_types.is_empty() {
        writeln!(
            output,
            "import type {{ {} }} from \"@runku/client\";\n",
            client_types.into_iter().collect::<Vec<_>>().join(", ")
        )
        .map_err(|_| BuildError::Internal)?;
    }
    output.push_str("export interface RunkuFunctions {\n");
    for function in functions {
        let name = quoted(function.name.as_str())?;
        let arguments = contract_type(&function.arguments_contract);
        let result = contract_type(&function.result_contract);
        let kind = match function.function_type {
            FunctionType::Query => "query",
            FunctionType::Mutation => "mutation",
            FunctionType::Action => "action",
        };
        let visibility = match function.visibility {
            FunctionVisibility::Public => "public",
            FunctionVisibility::Internal => "internal",
        };
        writeln!(
            output,
            "  readonly {name}: {{ readonly kind: \"{kind}\"; readonly visibility: \"{visibility}\"; readonly arguments: {arguments}; readonly result: {result} }};"
        )
        .map_err(|_| BuildError::Internal)?;
    }
    output.push_str("}\n\nexport interface RunkuDocuments {\n");
    for table in &schema.tables {
        let name = quoted(&table.name)?;
        let value = contract_type(&table.document_contract);
        writeln!(
            output,
            "  readonly {name}: {{ readonly tableId: \"{}\"; readonly indexes: {}; readonly value: {value} }};",
            table.id,
            generated_indexes(indexes, table.id)?,
        )
        .map_err(|_| BuildError::Internal)?;
    }
    output.push_str(
        "}\n\n\
export type RunkuFunctionName = keyof RunkuFunctions;\n\
export type RunkuFunctionArguments<N extends RunkuFunctionName> = RunkuFunctions[N][\"arguments\"];\n\
export type RunkuFunctionResult<N extends RunkuFunctionName> = RunkuFunctions[N][\"result\"];\n",
    );
    if output.len() > GENERATED_TYPES_MAX_BYTES {
        return Err(BuildError::LimitExceeded);
    }
    Ok(output.into_bytes())
}

fn collect_client_types(contract: &Contract, output: &mut BTreeSet<&'static str>) {
    match contract {
        Contract::Any => {
            output.insert("RunkuValue");
        }
        Contract::Timestamp => {
            output.insert("RunkuTimestamp");
        }
        Contract::TypedId { .. } => {
            output.insert("RunkuId");
        }
        Contract::DocumentId { .. } => {
            output.insert("DocumentId");
        }
        Contract::Array { items, .. } => collect_client_types(items, output),
        Contract::Object { fields, .. } => {
            for field in fields.values() {
                collect_client_types(field, output);
            }
        }
        Contract::Union { variants } => {
            for variant in variants {
                collect_client_types(variant, output);
            }
        }
        Contract::Null
        | Contract::Boolean
        | Contract::Int64 { .. }
        | Contract::Float64 { .. }
        | Contract::String { .. }
        | Contract::Bytes { .. } => {}
    }
}

fn generated_indexes(
    catalog: &SchemaCatalog,
    table_id: runku_core::TableId,
) -> Result<String, BuildError> {
    let mut output = String::from("{ ");
    for index in catalog.indexes_for_table(table_id) {
        let name = quoted(index.name())?;
        write!(output, "readonly {name}: \"{}\"; ", index.index_id())
            .map_err(|_| BuildError::Internal)?;
    }
    output.push('}');
    Ok(output)
}

fn contract_type(contract: &Contract) -> String {
    match contract {
        Contract::Any => "RunkuValue".to_owned(),
        Contract::Null => "null".to_owned(),
        Contract::Boolean => "boolean".to_owned(),
        Contract::Int64 { .. } => "bigint".to_owned(),
        Contract::Float64 { .. } => "number".to_owned(),
        Contract::String { .. } => "string".to_owned(),
        Contract::Bytes { .. } => "Uint8Array".to_owned(),
        Contract::Timestamp => "RunkuTimestamp".to_owned(),
        Contract::TypedId { kind } => kind.as_ref().map_or_else(
            || "RunkuId".to_owned(),
            |kind| format!("RunkuId & {{ readonly value: `{kind}_${{string}}` }}"),
        ),
        Contract::DocumentId { table } => format!(
            "DocumentId<{}>",
            serde_json::to_string(table).unwrap_or_else(|_| "\"invalid\"".to_owned())
        ),
        Contract::Array { items, .. } => {
            format!("readonly ({})[]", contract_type(items))
        }
        Contract::Object { fields, optional } => {
            let mut output = String::from("{ ");
            for (name, field) in fields {
                let quoted =
                    serde_json::to_string(name).unwrap_or_else(|_| "\"invalid\"".to_owned());
                let marker = if optional.contains(name) { "?" } else { "" };
                let _ = write!(
                    output,
                    "readonly {quoted}{marker}: {}; ",
                    contract_type(field)
                );
            }
            output.push('}');
            output
        }
        Contract::Union { variants } => variants
            .iter()
            .map(|variant| format!("({})", contract_type(variant)))
            .collect::<Vec<_>>()
            .join(" | "),
    }
}

fn quoted(value: &str) -> Result<String, BuildError> {
    serde_json::to_string(value).map_err(|_| BuildError::Internal)
}
