use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write,
};

use runku_contracts::{Contract, DocumentSchemaV1};
use runku_releases::{AuthPolicy, FunctionType, FunctionVisibility};
use runku_schema::SchemaCatalog;

use crate::{BuildError, declarative::LoadedFunction};

pub(crate) const GENERATED_TYPES_MAX_BYTES: usize = 2 * 1024 * 1024;

pub(crate) struct GeneratedApi {
    pub(crate) immutable_declarations: Vec<u8>,
    pub(crate) browser_declarations: Vec<u8>,
    pub(crate) browser_runtime: Vec<u8>,
    pub(crate) server_declarations: Vec<u8>,
    pub(crate) server_runtime: Vec<u8>,
}

pub(crate) fn generate_types(
    functions: &[LoadedFunction],
    schema: &DocumentSchemaV1,
    indexes: &SchemaCatalog,
) -> Result<GeneratedApi, BuildError> {
    let mut client_types = BTreeSet::new();
    for function in functions {
        collect_client_types(&function.arguments_contract, &mut client_types);
        collect_client_types(&function.result_contract, &mut client_types);
    }
    for table in &schema.tables {
        collect_client_types(&table.document_contract, &mut client_types);
    }
    let (immutable, output) = declarations(functions, schema, indexes, &client_types)?;
    let mut server_declarations = String::new();
    if client_types.is_empty() {
        server_declarations.push_str("import type { FunctionReference } from \"@runku/client\";\n");
    } else {
        writeln!(
            server_declarations,
            "import type {{ FunctionReference, {} }} from \"@runku/client\";",
            client_types.into_iter().collect::<Vec<_>>().join(", ")
        )
        .map_err(|_| BuildError::Internal)?;
    }
    server_declarations.push_str("export declare const serverApi: ");
    write_reference_tree(&mut server_declarations, functions, true)?;
    server_declarations.push_str(";\n");

    let browser_runtime = reference_runtime(functions, false)?;
    let server_runtime = reference_runtime(functions, true)?;
    if [
        immutable.len(),
        output.len(),
        server_declarations.len(),
        browser_runtime.len(),
        server_runtime.len(),
    ]
    .into_iter()
    .any(|size| size > GENERATED_TYPES_MAX_BYTES)
    {
        return Err(BuildError::LimitExceeded);
    }
    Ok(GeneratedApi {
        immutable_declarations: immutable.into_bytes(),
        browser_declarations: output.into_bytes(),
        browser_runtime: browser_runtime.into_bytes(),
        server_declarations: server_declarations.into_bytes(),
        server_runtime: server_runtime.into_bytes(),
    })
}

fn declarations(
    functions: &[LoadedFunction],
    schema: &DocumentSchemaV1,
    indexes: &SchemaCatalog,
    client_types: &BTreeSet<&'static str>,
) -> Result<(String, String), BuildError> {
    let mut immutable = String::from("// Generated by Runku. Do not edit.\n");
    let mut output = String::from("// Generated by Runku. Do not edit.\n");
    if !client_types.is_empty() {
        writeln!(
            immutable,
            "import type {{ {} }} from \"@runku/client\";\n",
            client_types.iter().copied().collect::<Vec<_>>().join(", ")
        )
        .map_err(|_| BuildError::Internal)?;
    }
    if client_types.is_empty() {
        output.push_str("import type { FunctionReference } from \"@runku/client\";\n");
    } else {
        writeln!(
            output,
            "import type {{ FunctionReference, {} }} from \"@runku/client\";\n",
            client_types.iter().copied().collect::<Vec<_>>().join(", ")
        )
        .map_err(|_| BuildError::Internal)?;
    }
    immutable.push_str("export interface RunkuFunctions {\n");
    output.push_str("export interface RunkuFunctions {\n");
    for function in functions {
        let name = quoted(function.name.as_str())?;
        let arguments = contract_type(&function.arguments_contract);
        let result = contract_type(&function.result_contract);
        let kind = match function.function_type {
            FunctionType::Query => "query",
            FunctionType::Mutation => "mutation",
            FunctionType::Action => "action",
        };
        let visibility = match function.visibility {
            FunctionVisibility::Public => "public",
            FunctionVisibility::Internal => "internal",
        };
        let auth = auth_name(function.auth_policy);
        writeln!(
            output,
            "  readonly {name}: {{ readonly kind: \"{kind}\"; readonly visibility: \"{visibility}\"; readonly auth: \"{auth}\"; readonly arguments: {arguments}; readonly result: {result} }};"
        )
        .map_err(|_| BuildError::Internal)?;
        writeln!(
            immutable,
            "  readonly {name}: {{ readonly kind: \"{kind}\"; readonly visibility: \"{visibility}\"; readonly arguments: {arguments}; readonly result: {result} }};"
        )
        .map_err(|_| BuildError::Internal)?;
    }
    immutable.push_str("}\n\nexport interface RunkuDocuments {\n");
    output.push_str("}\n\nexport interface RunkuDocuments {\n");
    for table in &schema.tables {
        let name = quoted(&table.name)?;
        let value = contract_type(&table.document_contract);
        writeln!(
            output,
            "  readonly {name}: {{ readonly tableId: \"{}\"; readonly indexes: {}; readonly value: {value} }};",
            table.id,
            generated_indexes(indexes, table.id)?,
        )
        .map_err(|_| BuildError::Internal)?;
        writeln!(
            immutable,
            "  readonly {name}: {{ readonly tableId: \"{}\"; readonly indexes: {}; readonly value: {value} }};",
            table.id,
            generated_indexes(indexes, table.id)?,
        )
        .map_err(|_| BuildError::Internal)?;
    }
    immutable.push_str(
        "}\n\n\
export type RunkuFunctionName = keyof RunkuFunctions;\n\
export type RunkuFunctionArguments<N extends RunkuFunctionName> = RunkuFunctions[N][\"arguments\"];\n\
export type RunkuFunctionResult<N extends RunkuFunctionName> = RunkuFunctions[N][\"result\"];\n",
    );
    output.push_str(
        "}\n\n\
export type RunkuFunctionName = keyof RunkuFunctions;\n\
export type RunkuFunctionArguments<N extends RunkuFunctionName> = RunkuFunctions[N][\"arguments\"];\n\
export type RunkuFunctionResult<N extends RunkuFunctionName> = RunkuFunctions[N][\"result\"];\n",
    );
    output.push_str("\nexport declare const api: ");
    write_reference_tree(&mut output, functions, false)?;
    output.push_str(";\n");
    Ok((immutable, output))
}

#[derive(Default)]
struct ReferenceTree<'a> {
    children: BTreeMap<&'a str, ReferenceTree<'a>>,
    function: Option<&'a LoadedFunction>,
}

fn reference_tree(
    functions: &[LoadedFunction],
    server: bool,
) -> Result<ReferenceTree<'_>, BuildError> {
    let mut root = ReferenceTree::default();
    for function in functions.iter().filter(|function| {
        function.visibility == FunctionVisibility::Public
            && (server || function.auth_policy != AuthPolicy::Service)
    }) {
        let segments = function.name.as_str().split(['.', '/']).collect::<Vec<_>>();
        if segments.iter().any(|segment| segment.is_empty()) {
            return Err(BuildError::InvalidConfig);
        }
        let mut node = &mut root;
        for segment in segments {
            node = node.children.entry(segment).or_default();
        }
        if node.function.replace(function).is_some() {
            return Err(BuildError::InvalidConfig);
        }
    }
    Ok(root)
}

fn write_reference_tree(
    output: &mut String,
    functions: &[LoadedFunction],
    server: bool,
) -> Result<(), BuildError> {
    let tree = reference_tree(functions, server)?;
    write_reference_node(output, &tree)
}

fn write_reference_node(output: &mut String, node: &ReferenceTree<'_>) -> Result<(), BuildError> {
    if let Some(function) = node.function {
        write!(
            output,
            "FunctionReference<\"{}\", {}, {}, \"{}\">",
            kind_name(function.function_type),
            contract_type(&function.arguments_contract),
            contract_type(&function.result_contract),
            auth_name(function.auth_policy),
        )
        .map_err(|_| BuildError::Internal)?;
        if node.children.is_empty() {
            return Ok(());
        }
        output.push_str(" & ");
    }
    output.push_str("{ ");
    for (name, child) in &node.children {
        write!(output, "readonly {}: ", quoted(name)?).map_err(|_| BuildError::Internal)?;
        write_reference_node(output, child)?;
        output.push_str("; ");
    }
    output.push('}');
    Ok(())
}

fn reference_runtime(functions: &[LoadedFunction], server: bool) -> Result<String, BuildError> {
    let tree = reference_tree(functions, server)?;
    let mut output = String::from(
        "// Generated by Runku. Do not edit.\nimport { functionReference } from \"@runku/client\";\nexport const ",
    );
    output.push_str(if server { "serverApi = " } else { "api = " });
    write_runtime_node(&mut output, &tree)?;
    output.push_str(";\n");
    Ok(output)
}

fn write_runtime_node(output: &mut String, node: &ReferenceTree<'_>) -> Result<(), BuildError> {
    if let Some(function) = node.function {
        if !node.children.is_empty() {
            output.push_str("Object.freeze(Object.assign(Object.create(null),");
        }
        write!(
            output,
            "functionReference({}, \"{}\", \"{}\")",
            quoted(function.name.as_str())?,
            kind_name(function.function_type),
            auth_name(function.auth_policy),
        )
        .map_err(|_| BuildError::Internal)?;
        if node.children.is_empty() {
            return Ok(());
        }
        output.push(',');
    }
    output.push_str("Object.freeze({");
    for (name, child) in &node.children {
        write!(output, "[{}]: ", quoted(name)?).map_err(|_| BuildError::Internal)?;
        write_runtime_node(output, child)?;
        output.push(',');
    }
    output.push_str("})");
    if node.function.is_some() {
        output.push_str("))");
    }
    Ok(())
}

const fn kind_name(value: FunctionType) -> &'static str {
    match value {
        FunctionType::Query => "query",
        FunctionType::Mutation => "mutation",
        FunctionType::Action => "action",
    }
}

const fn auth_name(value: AuthPolicy) -> &'static str {
    match value {
        AuthPolicy::None => "none",
        AuthPolicy::Optional => "optional",
        AuthPolicy::Guest => "guest",
        AuthPolicy::User => "user",
        AuthPolicy::Service => "service",
    }
}

fn collect_client_types(contract: &Contract, output: &mut BTreeSet<&'static str>) {
    match contract {
        Contract::Any => {
            output.insert("RunkuValue");
        }
        Contract::Timestamp => {
            output.insert("RunkuTimestamp");
        }
        Contract::TypedId { .. } => {
            output.insert("RunkuId");
        }
        Contract::DocumentId { .. } => {
            output.insert("DocumentId");
        }
        Contract::Array { items, .. } => collect_client_types(items, output),
        Contract::Object { fields, .. } => {
            for field in fields.values() {
                collect_client_types(field, output);
            }
        }
        Contract::Union { variants } => {
            for variant in variants {
                collect_client_types(variant, output);
            }
        }
        Contract::Null
        | Contract::Boolean
        | Contract::Int64 { .. }
        | Contract::Float64 { .. }
        | Contract::String { .. }
        | Contract::Bytes { .. } => {}
    }
}

fn generated_indexes(
    catalog: &SchemaCatalog,
    table_id: runku_core::TableId,
) -> Result<String, BuildError> {
    let mut output = String::from("{ ");
    for index in catalog.indexes_for_table(table_id) {
        let name = quoted(index.name())?;
        write!(output, "readonly {name}: \"{}\"; ", index.index_id())
            .map_err(|_| BuildError::Internal)?;
    }
    output.push('}');
    Ok(output)
}

fn contract_type(contract: &Contract) -> String {
    match contract {
        Contract::Any => "RunkuValue".to_owned(),
        Contract::Null => "null".to_owned(),
        Contract::Boolean => "boolean".to_owned(),
        Contract::Int64 { .. } => "bigint".to_owned(),
        Contract::Float64 { .. } => "number".to_owned(),
        Contract::String { .. } => "string".to_owned(),
        Contract::Bytes { .. } => "Uint8Array".to_owned(),
        Contract::Timestamp => "RunkuTimestamp".to_owned(),
        Contract::TypedId { kind } => kind.as_ref().map_or_else(
            || "RunkuId".to_owned(),
            |kind| format!("RunkuId & {{ readonly value: `{kind}_${{string}}` }}"),
        ),
        Contract::DocumentId { table } => format!(
            "DocumentId<{}>",
            serde_json::to_string(table).unwrap_or_else(|_| "\"invalid\"".to_owned())
        ),
        Contract::Array { items, .. } => {
            format!("readonly ({})[]", contract_type(items))
        }
        Contract::Object { fields, optional } => {
            let mut output = String::from("{ ");
            for (name, field) in fields {
                let quoted =
                    serde_json::to_string(name).unwrap_or_else(|_| "\"invalid\"".to_owned());
                let marker = if optional.contains(name) { "?" } else { "" };
                let _ = write!(
                    output,
                    "readonly {quoted}{marker}: {}; ",
                    contract_type(field)
                );
            }
            output.push('}');
            output
        }
        Contract::Union { variants } => variants
            .iter()
            .map(|variant| format!("({})", contract_type(variant)))
            .collect::<Vec<_>>()
            .join(" | "),
    }
}

fn quoted(value: &str) -> Result<String, BuildError> {
    serde_json::to_string(value).map_err(|_| BuildError::Internal)
}
